/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse3.pkg1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author amit
 */
public class addRecipent extends javax.swing.JFrame {

    public void addRecipent(){
    try {
            // TODO add your handling code here:
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=cse31;selectMethod=cursor", "sa", "123456");
            String data = "insert into recipent values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(data);
            
            
            ps.setString(1, namefield.getText());
           
            int age = Integer.parseInt(agefield.getText()); 
            ps.setInt(2, age);
            
            String gender;
            gender = genderbox.getSelectedItem().toString();
            ps.setString(3, gender);
             
            String division;
            division = divisionbox.getSelectedItem().toString();
            ps.setString(4, division);
           
            ps.setString(5, districtfield.getText());
            
            ps.setString(6, psfield.getText());
            
            ps.setString(7, pofield.getText());
            
            int post_code = Integer.parseInt(pcfield.getText()); 
            ps.setInt(8, post_code);
            
            
            ps.setString(9, phonefield.getText());
            
            ps.setString(10, emailfield.getText());
            
             int member = Integer.parseInt(memberfield.getText()); 
            ps.setInt(11, member);
            
            double income = Double.parseDouble(incomefield.getText()); 
            ps.setDouble(12, income);
            
             ps.setString(13, occupationfield.getText());
             
            double amount = Double.parseDouble(amountfield.getText()); 
            ps.setDouble(14, amount);
            
            
            
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
	    LocalDateTime now = LocalDateTime.now();
            String date = dtf.format(now).toString();
            
            ps.setString(15, date);
            
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "New Recipent Inserted Successfully !!!");
            
            namefield.setText("");
            agefield.setText("");
            phonefield.setText("");
            emailfield.setText("");
            districtfield.setText("");
            psfield.setText("");
            pofield.setText("");
            amountfield.setText("");
            pcfield.setText("");
            occupationfield.setText("");
            incomefield.setText("");
            memberfield.setText("");
            
            
            
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please insert all the field correctly.");
        }
    
}
    public addRecipent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        incomefield = new javax.swing.JTextField();
        agefield = new javax.swing.JTextField();
        genderbox = new javax.swing.JComboBox<>();
        divisionbox = new javax.swing.JComboBox<>();
        districtfield = new javax.swing.JTextField();
        psfield = new javax.swing.JTextField();
        pofield = new javax.swing.JTextField();
        pcfield = new javax.swing.JTextField();
        phonefield = new javax.swing.JTextField();
        emailfield = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        amountfield = new javax.swing.JTextField();
        memberfield = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        insert_photo = new javax.swing.JButton();
        insert = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        occupationfield = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        jLabel1.setText("ADD NEW RECIPENT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText(" Age");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Division");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText(" District");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 70, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Police Station");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Post Office");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Post Code");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 80, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Phone no");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Ammount Of Donation");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, 30));

        incomefield.setBackground(new java.awt.Color(102, 102, 255));
        incomefield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(incomefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 160, 30));

        agefield.setBackground(new java.awt.Color(102, 102, 255));
        agefield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(agefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 150, 30));

        genderbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        getContentPane().add(genderbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 150, 30));

        divisionbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        divisionbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka", "Chattagram", "Sylhet", "Barishal", "Rajshahi", "Khulna", "Mymensing", "Rangpur" }));
        getContentPane().add(divisionbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 150, 30));

        districtfield.setBackground(new java.awt.Color(102, 102, 255));
        districtfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(districtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 150, 30));

        psfield.setBackground(new java.awt.Color(102, 102, 255));
        psfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(psfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 150, 30));

        pofield.setBackground(new java.awt.Color(102, 102, 255));
        pofield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(pofield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 150, 30));

        pcfield.setBackground(new java.awt.Color(102, 102, 255));
        pcfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(pcfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 150, 30));

        phonefield.setBackground(new java.awt.Color(102, 102, 255));
        phonefield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(phonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 150, 30));

        emailfield.setBackground(new java.awt.Color(102, 102, 255));
        emailfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 150, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Occupation");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Family Member");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, 30));

        namefield.setBackground(new java.awt.Color(102, 102, 255));
        namefield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        getContentPane().add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 150, 30));

        amountfield.setBackground(new java.awt.Color(102, 102, 255));
        amountfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(amountfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 160, 30));

        memberfield.setBackground(new java.awt.Color(102, 102, 255));
        memberfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(memberfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 160, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Recipent Name");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 170, 160));

        back.setBackground(new java.awt.Color(102, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 110, 40));

        insert_photo.setBackground(new java.awt.Color(102, 0, 0));
        insert_photo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        insert_photo.setText("Insert Photo");
        getContentPane().add(insert_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 170, -1));

        insert.setBackground(new java.awt.Color(102, 0, 0));
        insert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        getContentPane().add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 150, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Yearly Income");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, 30));

        occupationfield.setBackground(new java.awt.Color(102, 102, 255));
        occupationfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(occupationfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 160, 30));

        background.setIcon(new javax.swing.ImageIcon("G:\\CSE 3.1\\LAB\\Database lab\\images\\add_recipent (1).jpg")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 800, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         operations ob = new operations();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
        addRecipent();
    }//GEN-LAST:event_insertActionPerformed

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addRecipent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addRecipent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addRecipent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addRecipent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addRecipent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agefield;
    private javax.swing.JTextField amountfield;
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JTextField districtfield;
    private javax.swing.JComboBox<String> divisionbox;
    private javax.swing.JTextField emailfield;
    private javax.swing.JComboBox<String> genderbox;
    private javax.swing.JTextField incomefield;
    private javax.swing.JButton insert;
    private javax.swing.JButton insert_photo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField memberfield;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField occupationfield;
    private javax.swing.JTextField pcfield;
    private javax.swing.JTextField phonefield;
    private javax.swing.JTextField pofield;
    private javax.swing.JTextField psfield;
    // End of variables declaration//GEN-END:variables
}
