/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse3.pkg1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author amit
 */
public class ejection_panel extends javax.swing.JFrame {

    /**
     * Creates new form ejection_panel
     */
    public ejection_panel() {
        initComponents();
    }
    
     public void delete_doner(){
         try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=cse31;selectMethod=cursor", "sa", "123456");
           Statement stmt = con.createStatement();
           
            String search = "delete  from doner where id = '"+donatorid.getText()+"' ";
            
            stmt.executeUpdate(search);
            JOptionPane.showMessageDialog(null, "Doner Deleted Successfully !!!");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Invalid ID");
        }
    }
     
      public void delete_recipient(){
         try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=cse31;selectMethod=cursor", "sa", "123456");
           Statement stmt = con.createStatement();
           
            String search = "delete  from recipent where id = '"+recipentid.getText()+"' ";
            
            stmt.executeUpdate(search);
            JOptionPane.showMessageDialog(null, "recipent Deleted Successfully !!!");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Invalid ID");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donatorid = new javax.swing.JTextField();
        recipentid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Delete = new javax.swing.JButton();
        delete_recipient = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Delete2 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        donatorid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(donatorid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 140, 30));

        recipentid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(recipentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 140, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Donator ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 150, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Recipient ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 150, 30));

        Delete.setBackground(new java.awt.Color(102, 0, 0));
        Delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Delete.setText("Home");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 90, -1));

        delete_recipient.setBackground(new java.awt.Color(102, 0, 0));
        delete_recipient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete_recipient.setText("Delete");
        delete_recipient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_recipientActionPerformed(evt);
            }
        });
        getContentPane().add(delete_recipient, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ejection Panel");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        Delete2.setBackground(new java.awt.Color(102, 0, 0));
        Delete2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Delete2.setText("Delete");
        Delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete2ActionPerformed(evt);
            }
        });
        getContentPane().add(Delete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        background.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon("G:\\CSE 3.1\\LAB\\Database lab\\images\\ejection (1).jpg")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        operations ob = new operations();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DeleteActionPerformed

    private void delete_recipientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_recipientActionPerformed
        // TODO add your handling code here:
        delete_recipient();
    }//GEN-LAST:event_delete_recipientActionPerformed

    private void Delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete2ActionPerformed
        // TODO add your handling code here:
        delete_doner();
    }//GEN-LAST:event_Delete2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejection_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejection_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejection_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejection_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejection_panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Delete2;
    private javax.swing.JLabel background;
    private javax.swing.JButton delete_recipient;
    private javax.swing.JTextField donatorid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField recipentid;
    // End of variables declaration//GEN-END:variables
}
