package cse3.pkg1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;  
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author amit
 */
public class login extends javax.swing.JFrame {

  
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        UserID = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        usertextfield = new javax.swing.JTextField();
        passwordfield = new javax.swing.JPasswordField();
        resetbtn = new javax.swing.JButton();
        loginbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabel1.setText("Sign In");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 160, 40));

        UserID.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        UserID.setText("User Name");
        getContentPane().add(UserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 120, 30));

        password.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        password.setText("Password");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 100, 20));

        usertextfield.setBackground(new java.awt.Color(51, 204, 0));
        usertextfield.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(usertextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 260, 40));

        passwordfield.setBackground(new java.awt.Color(51, 204, 0));
        passwordfield.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        passwordfield.setText("jPasswordField1");
        getContentPane().add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 260, 40));

        resetbtn.setBackground(new java.awt.Color(51, 153, 0));
        resetbtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        resetbtn.setText("Reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 90, 40));

        loginbtn.setBackground(new java.awt.Color(51, 153, 0));
        loginbtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 100, 40));

        exitbtn.setBackground(new java.awt.Color(51, 153, 0));
        exitbtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 80, 40));

        jLabel2.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        jLabel2.setText("Donation And Distribution System");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        background.setBackground(new java.awt.Color(0, 0, 255));
        background.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon("G:\\CSE 3.1\\LAB\\Database lab\\images\\login1.jpg")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 430));

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 150, 80, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        usertextfield.setText("");
        passwordfield.setText("");
    }//GEN-LAST:event_resetbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
         try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=CSE31;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            String sql = "Select * from ADMIN where UserName=? and Password = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, usertextfield.getText());
            pst.setString(2, passwordfield.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
               
                operations ob = new operations();
                ob.setVisible(true);
                this.dispose();
               
              
            }
            else{
                JOptionPane.showMessageDialog(null, "Username and password not Correct");
                        usertextfield.setText("");
                        passwordfield.setText("");
            } 
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
      
    }//GEN-LAST:event_loginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserID;
    private javax.swing.JLabel background;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginbtn;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JButton resetbtn;
    private javax.swing.JTextField usertextfield;
    // End of variables declaration//GEN-END:variables
}
