/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse3.pkg1;

/**
 *
 * @author amit
 */
public class operations extends javax.swing.JFrame {

    /**
     * Creates new form operations
     */
    public operations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_donator = new javax.swing.JButton();
        show_all = new javax.swing.JButton();
        add_recipient = new javax.swing.JButton();
        delete_recipient = new javax.swing.JButton();
        delete_recipient1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        delete_donator1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_donator.setBackground(new java.awt.Color(153, 0, 0));
        add_donator.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add_donator.setText("Add Donator");
        add_donator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_donatorActionPerformed(evt);
            }
        });
        getContentPane().add(add_donator, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 240, 50));

        show_all.setBackground(new java.awt.Color(0, 153, 0));
        show_all.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        show_all.setText("Show all Donners");
        show_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_allActionPerformed(evt);
            }
        });
        getContentPane().add(show_all, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 240, 50));

        add_recipient.setBackground(new java.awt.Color(153, 0, 0));
        add_recipient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add_recipient.setText("Add Recipient");
        add_recipient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_recipientActionPerformed(evt);
            }
        });
        getContentPane().add(add_recipient, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 220, 50));

        delete_recipient.setBackground(new java.awt.Color(153, 0, 0));
        delete_recipient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete_recipient.setText("Visit Donation Page");
        delete_recipient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_recipientActionPerformed(evt);
            }
        });
        getContentPane().add(delete_recipient, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 540, 50));

        delete_recipient1.setBackground(new java.awt.Color(153, 0, 0));
        delete_recipient1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete_recipient1.setText("Delete Recipient");
        delete_recipient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_recipient1ActionPerformed(evt);
            }
        });
        getContentPane().add(delete_recipient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 220, 50));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Search Recipient");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 220, 50));

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Search Donator");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 240, 50));

        delete_donator1.setBackground(new java.awt.Color(153, 0, 0));
        delete_donator1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete_donator1.setText("Delete Donator");
        delete_donator1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_donator1ActionPerformed(evt);
            }
        });
        getContentPane().add(delete_donator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 240, 50));

        jButton3.setBackground(new java.awt.Color(0, 153, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Show All Recipients");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 220, 50));

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        jLabel1.setText("Donation And Distribution System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        background.setBackground(new java.awt.Color(153, 0, 0));
        background.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon("G:\\CSE 3.1\\LAB\\Database lab\\images\\operations (1).jpg")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_donatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_donatorActionPerformed
        // TODO add your handling code here:
        addDonator ob = new addDonator();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_add_donatorActionPerformed

    private void show_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_allActionPerformed
        // TODO add your handling code here:
        display_doners ob = new display_doners();
        ob.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_show_allActionPerformed

    private void delete_recipientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_recipientActionPerformed
        // TODO add your handling code here:
        total ob = new total();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_delete_recipientActionPerformed

    private void add_recipientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_recipientActionPerformed
        // TODO add your handling code here:
        addRecipent ob = new addRecipent();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_add_recipientActionPerformed

    private void delete_recipient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_recipient1ActionPerformed
        // TODO add your handling code here:
        ejection_panel ob = new ejection_panel();
        ob.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_delete_recipient1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        search_and_update_recipent ob = new search_and_update_recipent();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        search_and_update_donators ob = new search_and_update_donators();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void delete_donator1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_donator1ActionPerformed
        // TODO add your handling code here:
        ejection_panel ob = new ejection_panel();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_delete_donator1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        display_recipents ob = new display_recipents();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new operations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_donator;
    private javax.swing.JButton add_recipient;
    private javax.swing.JLabel background;
    private javax.swing.JButton delete_donator1;
    private javax.swing.JButton delete_recipient;
    private javax.swing.JButton delete_recipient1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton show_all;
    // End of variables declaration//GEN-END:variables
}
