/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse3.pkg1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author amit
 */
public class search_and_update_donators extends javax.swing.JFrame {

    /**
     * Creates new form search_and_update_donators
     */
    
    public search_and_update_donators() {
        initComponents();
    }
    public void search_doner(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=cse31;selectMethod=cursor", "sa", "123456");
           Statement stmt = con.createStatement();
           // int studentId = Integer.parseInt(id.getText());
            String search = "select * from doner where id = '"+idfield.getText()+"' ";
             PreparedStatement ps = con.prepareStatement(search);
            ps.executeQuery();
            ResultSet rs = stmt.executeQuery(search);
             if(rs.next()){
                 namefield.setText(rs.getString("name"));
                 
                 agefield.setText(rs.getString("age"));
                 genderbox.setSelectedItem(rs.getString("gender"));
                 divisionbox.setSelectedItem(rs.getString("division"));
                 districtfield.setText(rs.getString("district"));
                 psfield.setText(rs.getString("police_station"));
                 pofield.setText(rs.getString("post_office"));
                 pcfield.setText(rs.getString("post_code"));
                 occupationbox.setSelectedItem(rs.getString("occupation"));
                 phonefield.setText(rs.getString("phone"));
                 emailfield.setText(rs.getString("email"));
                 amountfield.setText(rs.getString("amount_of_donation"));
                 datefield.setText(rs.getString("date"));
                 
             }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,  e);
        }
    }
    
    
     
    public void update_doner(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=cse31;selectMethod=cursor", "sa", "123456");
           
            String update = "update doner set name =?, age =?,gender =?,division =?,district =?,police_station =?,post_office =?,post_code =?,occupation=?,phone=?,email=?,amount_of_donation=? where id = '"+idfield.getText()+"' ";
             PreparedStatement ps = con.prepareStatement(update);
             ps.setString(1, namefield.getText());
              ps.setString(2, agefield.getText());
               ps.setString(3, (String)genderbox.getSelectedItem());
                ps.setString(4, (String) divisionbox.getSelectedItem());
                 ps.setString(5, districtfield.getText());
             
             ps.setString(6, psfield.getText());
              ps.setString(7, pofield.getText());
               ps.setString(8, pcfield.getText());
               ps.setString(9, (String) occupationbox.getSelectedItem());
               ps.setString(10, phonefield.getText());
               ps.setString(11, emailfield.getText());
                ps.setString(12, amountfield.getText());
             ps.executeUpdate();
             ps.close();
             JOptionPane.showMessageDialog(null, "Data Updated Successfully !!!");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Invalid ID");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        occupationbox = new javax.swing.JComboBox<>();
        divisionbox = new javax.swing.JComboBox<>();
        genderbox = new javax.swing.JComboBox<>();
        namefield = new javax.swing.JTextField();
        idfield = new javax.swing.JTextField();
        agefield = new javax.swing.JTextField();
        psfield = new javax.swing.JTextField();
        pofield = new javax.swing.JTextField();
        pcfield = new javax.swing.JTextField();
        phonefield = new javax.swing.JTextField();
        emailfield = new javax.swing.JTextField();
        amountfield = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        datefield = new javax.swing.JTextField();
        districtfield = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        occupationbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        occupationbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Engineer", "Doctor", "Teacher", "Businessman", "Student", "Housewife", "Lawyer" }));
        getContentPane().add(occupationbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 170, -1));

        divisionbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        divisionbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka", "Chattagram", "Sylhet", "Barishal", "Rajshahi", "Khulna", "Mymensing", "Rangpur" }));
        getContentPane().add(divisionbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 170, -1));

        genderbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        getContentPane().add(genderbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 170, 30));

        namefield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        getContentPane().add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 170, 30));

        idfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idfieldActionPerformed(evt);
            }
        });
        getContentPane().add(idfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 170, 30));

        agefield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(agefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 170, 30));

        psfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(psfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 170, 30));

        pofield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(pofield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 170, 30));

        pcfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(pcfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 170, 30));

        phonefield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(phonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 170, 30));

        emailfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 170, 30));

        amountfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(amountfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 170, 30));

        save.setBackground(new java.awt.Color(102, 0, 0));
        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 170, 40));

        datefield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(datefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 170, 30));

        districtfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(districtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 170, 30));

        search.setBackground(new java.awt.Color(102, 0, 0));
        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 110, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 170, 160));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Age");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Name");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Phone");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Date");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Amount Of Donation");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Occupation");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Post code");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Post Office");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Police Station");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("District");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Division");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Gender");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        jLabel1.setText("Search & Update Panel");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Donator ID");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Donator's Photograph");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 267, 160, 30));

        back.setBackground(new java.awt.Color(102, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setText("<Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, 110, 40));

        background.setIcon(new javax.swing.ImageIcon("G:\\CSE 3.1\\LAB\\Database lab\\images\\add-donator (1).jpg")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefieldActionPerformed

    private void idfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idfieldActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        search_doner();
    }//GEN-LAST:event_searchActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        operations ob = new operations();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        update_doner();
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search_and_update_donators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search_and_update_donators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search_and_update_donators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search_and_update_donators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_and_update_donators().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agefield;
    private javax.swing.JTextField amountfield;
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JTextField datefield;
    private javax.swing.JTextField districtfield;
    private javax.swing.JComboBox<String> divisionbox;
    private javax.swing.JTextField emailfield;
    private javax.swing.JComboBox<String> genderbox;
    private javax.swing.JTextField idfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField namefield;
    private javax.swing.JComboBox<String> occupationbox;
    private javax.swing.JTextField pcfield;
    private javax.swing.JTextField phonefield;
    private javax.swing.JTextField pofield;
    private javax.swing.JTextField psfield;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
