/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse3.pkg1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author amit
 */
public class search_and_update_recipent extends javax.swing.JFrame {

    /**
     * Creates new form search_and_update_recipent
     */
    public search_and_update_recipent() {
        initComponents();
    }
    public void search_recipent(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=cse31;selectMethod=cursor", "sa", "123456");
           Statement stmt = con.createStatement();
           // int studentId = Integer.parseInt(id.getText());
            String search = "select * from recipent where id = '"+idfield.getText()+"' ";
             PreparedStatement ps = con.prepareStatement(search);
            ps.executeQuery();
            ResultSet rs = stmt.executeQuery(search);
             if(rs.next()){
                 namefield.setText(rs.getString("name"));
                 
                 agefield.setText(rs.getString("age"));
                 genderbox.setSelectedItem(rs.getString("gender"));
                 divisionbox.setSelectedItem(rs.getString("division"));
                 districtfield.setText(rs.getString("district"));
                 police_stationfield.setText(rs.getString("police_station"));
                 pofield.setText(rs.getString("post_office"));
                 pcfield.setText(rs.getString("post_code"));
                 
                 phonefield.setText(rs.getString("phone"));
                 emailfield.setText(rs.getString("email"));
                 memberfield.setText(rs.getString("family_member"));
                 incomefield.setText(rs.getString("yearly_income"));
                 occupationfield.setText(rs.getString("occupation"));
                 datefield.setText(rs.getString("date"));
                 amountfield.setText(rs.getString("amount_of_donation"));
                 
                 
             }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,  e);
        }
    }
    
    
     public void update_recipient(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=cse31;selectMethod=cursor", "sa", "123456");
           
            String update = "update recipent set name =?, age =?,gender =?,division =?,district =?,police_station =?,post_office =?,post_code =?,phone=?,email=?,family_member=?,yearly_income=?,occupation=?,amount_of_donation=? where id = '"+idfield.getText()+"' ";
             PreparedStatement ps = con.prepareStatement(update);
             ps.setString(1, namefield.getText());
              ps.setString(2, agefield.getText());
               ps.setString(3, (String)genderbox.getSelectedItem());
                ps.setString(4, (String) divisionbox.getSelectedItem());
                 ps.setString(5, districtfield.getText());
             
             ps.setString(6, police_stationfield.getText());
              ps.setString(7, pofield.getText());
               ps.setString(8, pcfield.getText());
              // ps.setString(9, (String) occupationbox.getSelectedItem());
               ps.setString(9, phonefield.getText());
               ps.setString(10, emailfield.getText());
                ps.setString(11, memberfield.getText());
                 ps.setString(12, incomefield.getText());
                 ps.setString(13, occupationfield.getText());
                ps.setString(14, amountfield.getText());
             ps.executeUpdate();
             ps.close();
             JOptionPane.showMessageDialog(null, "Data Updated Successfully !!!");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Invalid ID");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pcfield = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        agefield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        idfield = new javax.swing.JTextField();
        districtfield = new javax.swing.JTextField();
        police_stationfield = new javax.swing.JTextField();
        incomefield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        phonefield = new javax.swing.JTextField();
        emailfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pofield = new javax.swing.JTextField();
        divisionbox = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        genderbox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        amountfield = new javax.swing.JTextField();
        memberfield = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        occupationfield = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        datefield = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        save1 = new javax.swing.JButton();
        psfield = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pcfield.setBackground(new java.awt.Color(102, 102, 255));
        pcfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(pcfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 150, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Phone no");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, 30));

        agefield.setBackground(new java.awt.Color(102, 102, 255));
        agefield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(agefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 150, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Division");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 30));

        idfield.setBackground(new java.awt.Color(102, 102, 255));
        idfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idfieldActionPerformed(evt);
            }
        });
        getContentPane().add(idfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 150, 30));

        districtfield.setBackground(new java.awt.Color(102, 102, 255));
        districtfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(districtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 150, 30));

        police_stationfield.setBackground(new java.awt.Color(102, 102, 255));
        police_stationfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(police_stationfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 150, 30));

        incomefield.setBackground(new java.awt.Color(102, 102, 255));
        incomefield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(incomefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 190, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Post Office");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Police Station");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Family Member");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, 30));

        phonefield.setBackground(new java.awt.Color(102, 102, 255));
        phonefield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(phonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 150, 30));

        emailfield.setBackground(new java.awt.Color(102, 102, 255));
        emailfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 150, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText(" Age");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 30));

        pofield.setBackground(new java.awt.Color(102, 102, 255));
        pofield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(pofield, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 150, 30));

        divisionbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        divisionbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka", "Chattagram", "Sylhet", "Barishal", "Rajshahi", "Khulna", "Mymensing", "Rangpur" }));
        getContentPane().add(divisionbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 150, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Occupation");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText(" District");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 70, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Ammount Of Donation");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Post Code");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 80, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 30));

        genderbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        getContentPane().add(genderbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 150, 30));

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        jLabel1.setText("Search & Update Panel");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, 40));

        amountfield.setBackground(new java.awt.Color(102, 102, 255));
        amountfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(amountfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 190, 30));

        memberfield.setBackground(new java.awt.Color(102, 102, 255));
        memberfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(memberfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 190, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Recipent ID");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 170, 160));

        back.setBackground(new java.awt.Color(102, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setText("<Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 110, 40));

        search.setBackground(new java.awt.Color(102, 0, 0));
        search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 140, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Yearly Income");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, 30));

        occupationfield.setBackground(new java.awt.Color(102, 102, 255));
        occupationfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(occupationfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 190, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Date");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, 30));

        datefield.setBackground(new java.awt.Color(102, 102, 255));
        datefield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(datefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 190, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Recipent's Photograph");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 160, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Recipent Name");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 30));

        namefield.setBackground(new java.awt.Color(102, 102, 255));
        namefield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        getContentPane().add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 150, 30));

        save1.setBackground(new java.awt.Color(102, 0, 0));
        save1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        save1.setText("SAVE");
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });
        getContentPane().add(save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, 150, 40));

        psfield.setIcon(new javax.swing.ImageIcon("G:\\CSE 3.1\\LAB\\Database lab\\images\\add_recipent (1).jpg")); // NOI18N
        getContentPane().add(psfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idfieldActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        operations ob = new operations();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        search_recipent();
    }//GEN-LAST:event_searchActionPerformed

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefieldActionPerformed

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
        // TODO add your handling code here:
        update_recipient();
    }//GEN-LAST:event_save1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search_and_update_recipent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search_and_update_recipent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search_and_update_recipent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search_and_update_recipent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_and_update_recipent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agefield;
    private javax.swing.JTextField amountfield;
    private javax.swing.JButton back;
    private javax.swing.JTextField datefield;
    private javax.swing.JTextField districtfield;
    private javax.swing.JComboBox<String> divisionbox;
    private javax.swing.JTextField emailfield;
    private javax.swing.JComboBox<String> genderbox;
    private javax.swing.JTextField idfield;
    private javax.swing.JTextField incomefield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField memberfield;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField occupationfield;
    private javax.swing.JTextField pcfield;
    private javax.swing.JTextField phonefield;
    private javax.swing.JTextField pofield;
    private javax.swing.JTextField police_stationfield;
    private javax.swing.JLabel psfield;
    private javax.swing.JButton save1;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
