/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cse3.pkg1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author amit
 */
public class total extends javax.swing.JFrame {

   
    /** Creates new form total */
    public total() {
        initComponents();
    }
    public void incomming_donation(){
       // double incomming_donation=0.00;
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=cse31;selectMethod=cursor", "sa", "123456");
           Statement stmt = con.createStatement();
           // int studentId = Integer.parseInt(id.getText());
            String sum = "select sum(amount_of_donation)  as total from doner";
             PreparedStatement ps = con.prepareStatement(sum);
            ps.executeQuery();
            ResultSet rs = stmt.executeQuery(sum);
             if(rs.next()){
                 incommingfield.setText(rs.getString("total"));
                  
             }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,  e);
        }
        
        
        
    }
    public void outgoing_donation(){
       // double incomming_donation=0.00;
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=cse31;selectMethod=cursor", "sa", "123456");
           Statement stmt = con.createStatement();
           // int studentId = Integer.parseInt(id.getText());
            String sum = "select sum(amount_of_donation)  as total from recipent";
             PreparedStatement ps = con.prepareStatement(sum);
            ps.executeQuery();
            ResultSet rs = stmt.executeQuery(sum);
             if(rs.next()){
                 outgoingfield.setText(rs.getString("total"));
                 
             }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,  e);
        }
        
        
        
    }
    public void balance(){
       try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=cse31;selectMethod=cursor", "sa", "123456");
           Statement stmt = con.createStatement();
           // int studentId = Integer.parseInt(id.getText());
            String x = "select sum(amount_of_donation)  from doner";            
            PreparedStatement ps = con.prepareStatement(x);
            ps.executeQuery();
            ResultSet rs = stmt.executeQuery(x);
            
            double bal1 = Double.parseDouble(x);
            String y = "select sum(amount_of_donation)  from recipent";
            PreparedStatement pps = con.prepareStatement(y);
            pps.executeQuery();
            ResultSet rrs = stmt.executeQuery(y);
            double bal2 = Double.parseDouble(y);
            double remaining_fund = bal1-bal2;
            
            String fund = Double.toString(remaining_fund);
            
            currentfield.setText(fund);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,  e);
        }
    }
    
    public void current(){
        String xx = incommingfield.getText();
        double take = Double.parseDouble(xx);
        String yy= outgoingfield.getText();
        double give = Double.parseDouble(yy);
        
        double remain = take-give;
        String zz = Double.toString(remain);
        currentfield.setText(zz);
       
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        incommingfield = new javax.swing.JTextField();
        currentfield = new javax.swing.JTextField();
        outgoingfield = new javax.swing.JTextField();
        outgoing = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        income = new javax.swing.JButton();
        current_balance = new javax.swing.JButton();
        backgrounddd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        incommingfield.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        incommingfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incommingfieldActionPerformed(evt);
            }
        });
        getContentPane().add(incommingfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 270, 40));

        currentfield.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        getContentPane().add(currentfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 270, 40));

        outgoingfield.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        getContentPane().add(outgoingfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 270, 40));

        outgoing.setBackground(new java.awt.Color(153, 0, 0));
        outgoing.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        outgoing.setText(" Total Outgoing Donation");
        outgoing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outgoingActionPerformed(evt);
            }
        });
        getContentPane().add(outgoing, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 400, 40));

        home.setBackground(new java.awt.Color(153, 0, 0));
        home.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, -1, 30));

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, -1, 30));

        income.setBackground(new java.awt.Color(153, 0, 0));
        income.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        income.setText(" Total Incomming Donation");
        income.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeActionPerformed(evt);
            }
        });
        getContentPane().add(income, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 400, 40));

        current_balance.setBackground(new java.awt.Color(153, 0, 0));
        current_balance.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        current_balance.setText("Current Balance");
        current_balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                current_balanceActionPerformed(evt);
            }
        });
        getContentPane().add(current_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 390, 40));

        backgrounddd.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        backgrounddd.setIcon(new javax.swing.ImageIcon("G:\\CSE 3.1\\LAB\\Database lab\\images\\total().jpg")); // NOI18N
        getContentPane().add(backgrounddd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void incommingfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incommingfieldActionPerformed
        // TODO add your handling code here:
        incommingfield.disable();
    }//GEN-LAST:event_incommingfieldActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        operations ob = new operations();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed
 
    private void outgoingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outgoingActionPerformed
       outgoing_donation();
    }//GEN-LAST:event_outgoingActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        login ob = new login();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void incomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeActionPerformed
        incomming_donation();
    }//GEN-LAST:event_incomeActionPerformed

    private void current_balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_current_balanceActionPerformed
        // TODO add your handling code here:
        current();
    }//GEN-LAST:event_current_balanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new total().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgrounddd;
    private javax.swing.JButton current_balance;
    private javax.swing.JTextField currentfield;
    private javax.swing.JButton home;
    private javax.swing.JButton income;
    private javax.swing.JTextField incommingfield;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton outgoing;
    private javax.swing.JTextField outgoingfield;
    // End of variables declaration//GEN-END:variables

}
